### ISSUE TITLE
Make KO_DOCKER_REPO configurable

### ISSUE THREAD

**Issue by embano1** [imjasonh/setup-ko#1]
It would be nice to have `KO_DOCKER_REPO` being part of the inputs, e.g.

```yaml
- uses: imjasonh/setup-ko@v0.3
  with:
    version: v0.8.0
    KO_DOCKER_REPO: kind.local # later passed/injected as env var
```

This would avoid an additional step for the user to export the variable.
